name: ServerUtilitiesPlugin
version: '${project.version}'
main: plugin.serverutilitiesplugin.ServerUtilitiesPlugin
api-version: '1.20'
commands:
  serverutils:
    usage: /serverutils <args>
    permission: op
  whisper:
    usage: /whisper <player> <message>
    aliases:
      - w
      - tell
      - msg
  reply:
    usage: /reply <message>
    aliases:
      - r
  afk:
    usage: /afk